<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    
    <xacro:property name="footprint_radius" value="0.001" />
    <xacro:property name="baselink_radius" value="0.1" />
    <xacro:property name="baselink_length" value="0.08" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:property name="base_joint_z" value="${baselink_length/2+lidi}" />
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>
    <!-- 2.1 link -->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.08" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="baselink_color">
                <color rgba="1.0 0.5 0.2 0.5" />
            </material>
        </visual>
    </link>
    <!-- 2.2 joint -->
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <!-- 关节z上的设置 = 车体高度/2 + 离地间距 -->
        <origin xyz="0 0 ${base_joint_z}" rpy="0 0 0" />
    </joint>

    <!-- 属性 -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="wheel_joint_z" value="${-1*(baselink_length/2 + lidi - wheel_radius)}" />
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <!-- 注意:结果是负数 -->
        <!-- 3.1 link -->
        <!-- 
            wheel_name: left 或者 right
                  flag:    1 或者 -1
         -->
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <material name="${wheel_name}_color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>
        
        <!-- 3.2 joint -->
        <joint name="${wheel_name}2baselink" type="continuous">
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <origin xyz="0 ${0.1*flag} ${wheel_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />
    
    <xacro:macro name="small_wheel_func" params="small_wheel_name flag">
        <xacro:property name="small_wheel_radius" value="0.0075" />
        <xacro:property name="small_joint_x" value="0.08" />
        <xacro:property name="small_joint_z" value="${(baselink_length/2+lidi-small_wheel_radius)*-1}" />
        <!-- 4.1 link -->
        <link name="${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${small_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="wheel_color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>
        <!-- 4.2 joint-->
        <joint name="${small_wheel_name}2baselink" type="continuous">
            <parent link="base_link" />
            <child link="${small_wheel_name}_wheel" />
            <origin xyz="${small_joint_x * flag} 0 ${small_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <xacro:small_wheel_func small_wheel_name="front" flag="1" />
    <xacro:small_wheel_func small_wheel_name="back" flag="-1" />

</robot>